{{- if .Values.backend.enabled  }}
{{- range $j, $d := .Values.backend.deployments }}
{{ $kafkaClusterName := $d.kafka.clusterName }}
{{- if $d.kafka.enabled  }}
apiVersion: composition.krateo.io/v0-1-0
kind: CloudNativeKafkaTopic
metadata:
  name: {{ .Release.Name }}
spec:
  kafka:
    clusterName: {{ $kafkaClusterName }}
    topics:
    {{- toYaml $d.kafka.topics | nindent 6 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}