{{ $kafkaClusterName := .Values.kafka.clusterName }}
{{- range $i, $v := .Vaues.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $v.topicName }}
  labels:
    strimzi.io/cluster: {{ $kafkaClusterName }}
spec:
  partitions: {{ $v.partitions }}
  replicas: {{ $v.replicas }}
---
{{- end }}