{{- if .Values.cloudnativepg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cloudnativepg.clusterName | quote }}
spec:
  instances: {{ .Values.cloudnativepg.instances }}
  storage:
    size: {{ .Values.cloudnativepg.storageSize | quote }}
  bootstrap:
    initdb:
      database: {{ .Values.cloudnativepg.databaseName | quote }}
      owner: {{ .Values.cloudnativepg.user | quote }}
  managed:
    services:
      ## disable the default services
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: {{ .Values.cloudnativepg.clusterName }}-lb-rw
            spec:
              type: LoadBalancer
{{- end }}