{{- if .Values.backend.enabled }}
{{- range $j, $d := .Values.backend.deployments }}
{{- if $d.cloudnativepg.enabled }}
{{- range $i, $v := $d.cloudnativepg.clusters }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $v.clusterName }}
spec:
  instances: {{ $v.instances }}
  storage:
    size: {{ $v.storageSize }}
  bootstrap:
    initdb:
      database: {{ $v.databaseName }}
      owner: {{ $v.user }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}