{{- if .Values.cloudnativepg.enabled }}
{{- range $i, $v := .Values.cloudnativepg.clusters }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ $v.clusterName }}
spec:
  instances: {{ $v.instances }}
  storage:
    size: {{ $v.storageSize }}
  bootstrap:
    initdb:
      database: {{ $v.databaseName }}
      owner: {{ $v.user }}
---
{{- end }}
{{- end }}