{{ $name := .Release.Name }}
{{- range $j, $d := .Values.backend.deployments }}
{{- range $i, $v := $d.cloudnativepg.instances }}
apiVersion: composition.krateo.io/v0-1-0
kind: Cloudnativepg
metadata:
  name: {{ $name }}-{{ $v.clusterName }}
spec:
  clusterName: {{ $v.clusterName }}
  replicas: {{ $v.replicas }}
  storageSize: {{ $v.storageSize }}
  databaseName: {{ $v.databaseName }}
  user: {{ $v.user }}
---
{{- end }}
{{- end }}