{{ $name := .Release.Name }}
{{ $namespace := .Release.Namespace }}
{{- $gracefullyPaused := default false (and .Values.global .Values.global.gracefullyPaused) }}
{{- with .Values.backend }}
{{- with .deployments }}
{{- range $j, $d := . }}
{{ with $d.kafka }}
{{- if gt ( len .topics ) 0 -}}
{{- $cluster := lookup "kafka.strimzi.io/v1beta2" "KafkaCluster" $namespace $name -}}
{{- if not $cluster -}}
apiVersion: composition.krateo.io/v0-1-0
kind: KafkaCluster
metadata:
  name: {{ $name }}-{{ $d.name }}-kfccomp
  annotations:
    krateo.io/paused: "{{ $gracefullyPaused }}"
spec:
  kafka:
    clusterName: {{ $name }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}