{{- if .Values.backend.enabled  }}
{{ $name := .Release.Name }}
{{- range $j, $d := .Values.backend.deployments }}
{{- if $d.kafka.enabled  }}
apiVersion: composition.krateo.io/v0-1-0
kind: KafkaCluster
metadata:
  name: {{ $name }}-{{ $d.name }}
spec:
  kafka:
    clusterName: {{ $name }}
---
{{- end }}
{{- end }}
{{- end }}