{{ $name := .Release.Name }}
{{- range $j, $d := .Values.backend.deployments }}
apiVersion: composition.krateo.io/v0-1-0
kind: KafkaTopic
metadata:
  name: {{ $name }}-{{ $d.name }}
spec:
  kafka:
    clusterName: {{ $name }}
    topics:
    {{- toYaml $d.kafka.topics | nindent 6 }}
---
{{- end }}