{{ $name := .Release.Name }}
{{- with .Values.backend }}
{{- with .deployments }}
{{- range $j, $d := . }}
{{ with $d.kafka }}
{{- if gt ( len .topics ) 0 -}}
apiVersion: composition.krateo.io/v0-1-0
kind: KafkaCluster
metadata:
  name: {{ $name }}-{{ $d.name }}
spec:
  kafka:
    clusterName: {{ $name }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}