{{- $name := .Release.Name }}
{{- with .Values.backend }}
{{- with .deployments }}
{{- range $j, $d := . }}
apiVersion: composition.krateo.io/v0-1-0
kind: KafkaTopic
metadata:
  name: {{ $name }}-{{ $d.name }}
spec:
  kafka:
    clusterName: {{ $name }}
    {{ with $d.kafka }}
    topics:
{{- toYaml .topics | nindent 6 }}
    {{ end }}
---
{{- end }}
{{- end }}
{{- end }}