{{ $name := .Release.Name }}
{{- $gracefullyPaused := default false (and .Values.global .Values.global.gracefullyPaused) }}
{{- with .Values.backend }}
{{- with .deployments }}
{{- range $j, $d := . }}
{{- with $d.cloudnativepg }}
{{- with .instances }}
{{- range $i, $v := . }}
apiVersion: composition.krateo.io/v0-1-0
kind: Cloudnativepg
metadata:
  name: {{ $name }}-{{ $v.clusterName }}-{{ $chartName }}
  annotations:
    krateo.io/paused: "{{ $gracefullyPaused }}"
spec:
  clusterName: {{ $v.clusterName }}
  replicas: {{ $v.replicas }}
  storageSize: {{ $v.storageSize }}
  databaseName: {{ $v.databaseName }}
  user: {{ $v.user }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}