{{- $name := .Release.Name }}
{{- $gracefullyPaused := default false (and .Values.global .Values.global.gracefullyPaused) }}
{{- with .Values.backend }}
{{- with .deployments }}
{{- range $j, $d := . }}
{{ with $d.kafka }}
{{- if gt ( len .topics ) 0 -}}
apiVersion: composition.krateo.io/v0-1-0
kind: KafkaTopic
metadata:
  name: {{ $name }}-{{ $d.name }}-{{ $chartName }}
  annotations:
    krateo.io/paused: "{{ $gracefullyPaused }}"
spec:
  kafka:
    clusterName: {{ $name }}
    topics:
{{- toYaml .topics | nindent 6 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}