{{ $name := .Release.Name }}
{{- with .Values.backend }}
{{- with .deployments }}
{{- range $j, $d := . }}
{{ $repository := $d.hazelcast.repository }}
{{ $version := $d.hazelcast.version }}
{{ $licenseKey := $d.hazelcast.licenseKey }}
{{- with $d.hazelcast.clusters }}
{{- range $i, $v := . }}
apiVersion: composition.krateo.io/v0-1-0
kind: Hazelcast
metadata:
  name: {{ $name }}-{{ $v.name }}
spec:
  licenseKey: {{ $licenseKey }}
  repository: {{ $repository }}
  version: {{ $version }}
  cluster:
    name: {{ $v.name }}
    size: {{ $v.size }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}