{{- if .Values.hazelcast.enabled }}
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{ .Values.hazelcast.clusterName }}
spec:
  clusterSize: {{ .Values.hazelcast.clusterSize }}
  clusterName: {{ .Values.hazelcast.clusterName }}
  repository: {{ .Values.hazelcast.repository }}
  version: {{ .Values.hazelcast.version }}
  licenseKeySecretName: {{ .Values.hazelcast.clusterName }}-license-key
  exposeExternally:
    type: Smart
    discoveryServiceType: LoadBalancer
{{- end }}