{{- if .Values.backend.enabled }}
{{ $namespace := .Release.Namespace }}
{{- range $j, $d := .Values.backend.deployments }}
{{- if $d.hazelcast.enabled }}
{{ $repository := $d.hazelcast.repository }}
{{ $version := $d.hazelcast.version }}
{{ $licenseKeyName := $d.hazelcast.licenseKeyName }}
{{- range $i, $v := $d.hazelcast.clusters }}
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: {{ $v.name }}
spec:
  clusterSize: {{ $v.size }}
  clusterName: {{ $v.name }}
  repository: {{ $repository }}
  version: {{ $version }}
  licenseKeySecretName: {{ $licenseKeyName }}
---
apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: {{ $v.name }}-mc
spec:
  repository: 'hazelcast/management-center'
  version: '5.9.0'
  licenseKeySecretName: {{ $licenseKeyName }}
  externalConnectivity:
    type: LoadBalancer
  hazelcastClusters:
  - address: {{ $v.name }}.{{ $namespace }}:5701
    name: {{ $v.name }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}