{{- if .Values.backend.enabled  }}
{{- range $j, $d := .Values.backend.deployments }}
{{ $kafkaClusterName := $d.kafka.clusterName }}
{{- if $d.kafka.enabled  }}
{{- range $i, $v := $d.kafka.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $v.topicName }}
  labels:
    strimzi.io/cluster: {{ $kafkaClusterName }}
spec:
  partitions: {{ $v.partitions }}
  replicas: {{ $v.replicas }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}