apiVersion: "v1"
kind: Secret
metadata:
  name: github-api
  namespace: cloudnative-stack-system
stringData:
  server-url: https://api.github.com
---
apiVersion: templates.krateo.io/v1
kind: RESTAction
metadata:
  name: get-features
  namespace: cloudnative-stack-system
spec:
  api:
  - name: features
    verb: GET
    headers:
    - 'Accept: application/vnd.github+json'
    - 'X-GitHub-Api-Version: 2022-11-28'
    path: "/search/repositories?q=org:krateoplatformops-test+topic:feature+topic:frontend"
    endpointRef:
      name: github-api
      namespace: cloudnative-stack-system
    filter: |
      .features.items | map((.name | sub("-feature$"; "")))